function ComparissonsPublicationsInitialFinal(data1, data2)
%CREATEFIGURE(DATA1, DATA2)
%  DATA1:  histogram data
%  DATA2:  histogram data

%  Auto-generated by MATLAB on 27-Apr-2015 13:40:34

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
box(axes1,'on');
hold(axes1,'on');

% Create ylabel
ylabel('Number of scientists','FontSize',16);

% Create xlabel
xlabel('Number of publications','FontSize',16);

% Create title
title('Evolution of publications per scientist',...
    'FontSize',16);

% Create histogram
histogram(data1,'DisplayName','Initial publications','Parent',axes1,...
    'EdgeColor',[0 0 0],...
    'FaceColor','black',...
    'Normalization','count',...
    'BinMethod','auto');

% Create histogram
histogram(data2,'DisplayName','Final publications','Parent',axes1,...
    'EdgeColor',[0 0 0],...
    'FaceColor','auto',...
    'Normalization','count',...
    'BinMethod','auto');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.727586059088498 0.777653880463872 0.141135764093861 0.118421052631579],...
    'FontSize',16);

