function ComparissonsPublishedUnpublished(data1, data2)
%CREATEFIGURE(DATA1, DATA2)
%  DATA1:  histogram data
%  DATA2:  histogram data

%  Auto-generated by MATLAB on 27-Apr-2015 13:17:01

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
%% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[0 4]);
box(axes1,'on');
hold(axes1,'on');

% Create ylabel
ylabel('Number of papers','FontSize',16);

% Create xlabel
xlabel('Quality of papers','FontSize',16);

% Create title
title('Quality of Published vs Unpublished','FontSize',16);

% Create histogram
histogram(data1,'DisplayName','Published papers','Parent',axes1,'EdgeColor',[0 0 0],'FaceColor','black',...
    'Normalization','count',...
    'BinMethod','auto');

% Create histogram
histogram(data2,'DisplayName','Unpublished papers','Parent',axes1,'EdgeColor',[0 0 0],'FaceColor','auto',...
    'Normalization','count',...
    'BinMethod','auto');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.680462667034933 0.734426229508197 0.206742720170454 0.157377049180328],...
    'FontSize',16);

