function EditorialRejectionRatesComparisson(data1, data2)
%CREATEFIGURE(DATA1, DATA2, X1, Y1, X2, Y2)
%  DATA1:  histogram data
%  DATA2:  histogram data
%  X1:  stairs x
%  Y1:  stairs y
%  X2:  stairs x
%  Y2:  stairs y

%  Auto-generated by MATLAB on 28-Apr-2015 14:04:49

% Create figure
figure1 = figure('Name','In-house rejection rates comparisson');

% Create subplot
subplot1 = subplot(2,1,1,'Parent',figure1);
box(subplot1,'on');
hold(subplot1,'on');

% Create ylabel
ylabel('Number of journals','FontSize',16);

% Create xlabel
xlabel('In-house rejection rates','FontSize',16);

% Create title
title('In-house rejection rates comparisson','FontSize',16);

% Create histogram
histogram(data1,'DisplayName','Simulations','Parent',subplot1,...
    'EdgeColor',[0 0 0],...
    'FaceColor','auto',...
    'Normalization','count',...
    'BinWidth',0.0069);

% Create histogram
histogram(data2,'DisplayName','Survey','Parent',subplot1,...
    'EdgeColor',[0 0 0],...
    'FaceColor','auto',...
    'Normalization','count',...
    'BinWidth',0.00811);

% Create legend
legend1 = legend(subplot1,'show');
set(legend1,...
    'Position',[0.69022000751798 0.828698559697367 0.186786469959078 0.0723562152133581],...
    'FontSize',16);

% Create subplot
subplot2 = subplot(2,1,2,'Parent',figure1);
box(subplot2,'on');
hold(subplot2,'on');

% Create ylabel
ylabel('F(x)','FontSize',16);

% Create xlabel
xlabel('x','FontSize',16);

% Create title
title('ECDF','FontSize',16);

% Create stairs
ecdf(data1)

% Create stairs
ecdf(data2)
