[ qualityOfPapers, shouldBePublished, resourcesCounter ] = CleanZeros( qualityOfPapers, shouldBePublished, numberOfPapers, resourcesCounter );

clear  authorBias                       resourcesParameter        sclContributionToQuality ...
       sclParameter                     thresholdParameter        thirdReviewerProbability ...
       epsilon                          scientistsPopulation      resourcesContributionToQuality ...
       journal                          journalToSubmit           qualityEvaluated ...
       reviewerIndex                    time                      author ...
       iPublish                         qualityOfPaper            resourcesInvested ...
       reviewer                         scientistLevel            scientistsToPublish ...
       update                           resubmissionProbability   totalResourcesInvested ...
       acceptance                       editorialRejection        thresholdParameterLow ...
       thresholdParameterHigh           reviewersIndexes          weeklySubmissions ...
       totalScientificInformationTemp   resubmissions             timeSpent ...
       weeklyResubmissionFlow           reviewers                 scientist ...
       decision                         index                     weeksInAYear ...
       years                            reinitialisation          historyOfPapers ...
       